In [27]:
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.api.types import is_numeric_dtype

df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

print("Total rows:", len(df))

Total rows: 1470

In [25]:
# check for missing values
has_missing_values = False
for c in df.columns:
    if df[c].isna().sum() != 0:
        print(f"{c} has {df[c].isna().sum()} missing values")
        has_missing_values = True
    
if not has_missing_values:
    print("The dataframe has no missing values")

The dataframe has no missing values

In [37]:
#check for outliers
print("The dataframe has these outliers: ")

for c in df.columns:
    if is_numeric_dtype(df[c]):
        q1 = df[c].quantile(0.25)
        q3 = df[c].quantile(0.75)
        IQR = q3 - q1
        outliers = df[c][((df[c] < (q1 - 1.5 * IQR)) | (df[c] > (q3 + 1.5 * IQR)))]
        if not outliers.empty:
            print(outliers)
            print("test \n")

The dataframe has these outliers:
25      19094
29      18947
45      19545
62      18740
105     18844
        ...
1374    17875
1377    19161
1401    19636
1437    19431
1443    18880
Name: MonthlyIncome, Length: 114, dtype: int64
test

4       9
38      9
50      9
95      9
105     9
122     9
194     9
198     9
208     9
245     9
287     9
290     9
334     9
371     9
372     9
385     9
393     9
401     9
440     9
447     9
456     9
525     9
541     9
544     9
551     9
575     9
597     9
617     9
623     9
660     9
714     9
717     9
756     9
770     9
779     9
789     9
816     9
837     9
927     9
947     9
957     9
1000    9
1035    9
1117    9
1145    9
1162    9
1172    9
1219    9
1262    9
1296    9
1357    9
1442    9
Name: NumCompaniesWorked, dtype: int64
test

1       4
6       4
7       4
8       4
21      4
       ..
1441    4
1445    4
1446    4
1447    4
1467    4
Name: PerformanceRating, Length: 226, dtype: int64
test

6       3
64      3
65      3
83      3
88      3
       ..
1402    3
1415    3
1440    3
1442    3
1457    3
Name: StockOptionLevel, Length: 85, dtype: int64
test

18      31
62      29
85      37
98      38
105     30
        ..
1264    34
1301    37
1331    29
1374    29
1401    35
Name: TotalWorkingYears, Length: 63, dtype: int64
test

0       0
10      5
16      5
20      5
23      6
       ..
1436    6
1448    5
1458    5
1466    5
1467    0
Name: TrainingTimesLastYear, Length: 238, dtype: int64
test

18      25
28      22
45      22
62      27
63      21
        ..
1403    20
1404    20
1443    22
1445    20
1462    20
Name: YearsAtCompany, Length: 104, dtype: int64
test

45      15
63      16
123     18
187     15
190     18
231     17
281     16
417     15
466     16
595     15
716     16
746     16
861     15
976     16
1024    17
1150    15
1156    15
1221    15
1327    17
1351    17
1430    16
Name: YearsInCurrentRole, dtype: int64
test

15       8
45      15
46       8
55       8
61       9
        ..
1414    12
1425     8
1444     9
1447    11
1462     9
Name: YearsSinceLastPromotion, Length: 107, dtype: int64
test

28      17
123     15
153     15
187     15
231     15
386     17
561     16
616     17
635     15
686     17
875     17
926     17
1078    17
1348    16
Name: YearsWithCurrManager, dtype: int64
test